name: CD - Deploy to S3
on:
  push:
    branches:
      - master
jobs:
  deploy-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from CI
        uses: actions/download-artifact@v4
        with:
          name: vite-build
          path: dist
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_S3_REGION }}
      - name: Sync to S3
        run: aws s3 sync dist/ s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete
